#!/usr/bin/env bash
#fizz buzz
x=1
while [ $x -le 100 ]
do
	if [ $((x%3)) == 0 ] && [ $((x%5)) == 0 ]
then
	echo "FizzBuzz"
	((x++))
elif [ $((x%3)) == 0 ]
then
	echo "Fizz"
	((x++))
elif [ $((x%5)) == 0 ]
then
	echo "Buzz"
	((x++))
else
	echo "$x"
	((x++))
	fi
done
